// AUTO-GENERATED by chrome-ui-registry-builder. Do not edit.
import button from "../../packages/registry/button/meta";
import dialog from "../../packages/registry/dialog/meta";
import select from "../../packages/registry/select/meta";
import theme from "../../packages/registry/_shared/theme/meta";
import utils from "../../packages/registry/_shared/utils/meta";

export const REGISTRY = [button, dialog, select, theme, utils];
