// AUTO-GENERATED by chrome-ui-registry-builder. Do not edit.
import theme from "../../packages/registry/_shared/theme/meta";
import utils from "../../packages/registry/_shared/utils/meta";

export const REGISTRY = [theme, utils];
