import { writeFile } from "node:fs/promises";

export interface ManifestEntry {
  name: string;
  /** TS-import-friendly relative path (no extension), as it should appear in `import ... from "..."` */
  relativeImportPath: string;
}

function toIdent(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

export async function writeManifest(
  outPath: string,
  entries: ManifestEntry[],
): Promise<void> {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const imports = sorted
    .map((e) => `import ${toIdent(e.name)} from "${e.relativeImportPath}";`)
    .join("\n");
  const list = sorted.map((e) => toIdent(e.name)).join(", ");
  const body = `// AUTO-GENERATED by chrome-ui-registry-builder. Do not edit.
${imports}

export const REGISTRY = [${list}];
`;
  await writeFile(outPath, body);
}
