import { writeFile } from "node:fs/promises";

export interface ManifestEntry {
  name: string;
  /** TS-import-friendly relative path (no extension), as it should appear in `import ... from "..."` */
  relativeImportPath: string;
}

function toIdent(name: string): string {
  const ident = name.replace(/[^a-zA-Z0-9_]/g, "_");
  // Idents can't start with a digit; prefix so e.g. `3d-card` → `_3d_card`.
  return /^[0-9]/.test(ident) ? `_${ident}` : ident;
}

export async function writeManifest(
  outPath: string,
  entries: ManifestEntry[],
): Promise<void> {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));

  // Distinct names can collapse to the same identifier (e.g. `my-x` and `my_x`),
  // which would emit a duplicate-import TS error. Fail loudly instead.
  const idents = new Map<string, string>();
  for (const e of sorted) {
    const ident = toIdent(e.name);
    const prev = idents.get(ident);
    if (prev && prev !== e.name) {
      throw new Error(
        `manifest identifier collision: "${prev}" and "${e.name}" both map to "${ident}"`,
      );
    }
    idents.set(ident, e.name);
  }

  const imports = sorted
    .map((e) => `import ${toIdent(e.name)} from ${JSON.stringify(e.relativeImportPath)};`)
    .join("\n");
  const list = sorted.map((e) => toIdent(e.name)).join(", ");
  const body = `// AUTO-GENERATED by chrome-ui-registry-builder. Do not edit.
${imports}

export const REGISTRY = [${list}];
`;
  await writeFile(outPath, body);
}
